version: '3.7' 
services:
  server:
    image: 'api:latest'
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8003:8003'
    volumes:
      - .:/app
    environment:
      - DATABASE_URL="${DATABASE_URL}"
    networks:
      - vrap
  client:
    image: 'client:latest'
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    volumes:
      - .:/app
    environment:
      - BASE_URL="${BASE_URL}"
    depends_on:
      - server
    networks:
      - vrap
    

networks:
  
  vrap:
    external:
      name: vrap
    
      